### ISSUE TITLE
Create a daily update

### ISSUE THREAD

**Issue by mazonk** [DECK1xUCN/DispatchApp#42]

**Comment by Piratepie** [comment]
done and working now 
![image](https://user-images.githubusercontent.com/27888345/236705906-d647e347-b452-4abc-8a82-aff27a10e56a.png)
![image](https://user-images.githubusercontent.com/27888345/236705919-130ef03a-a015-4673-a2b2-bcac79764dc1.png)
![image](https://user-images.githubusercontent.com/27888345/236705928-c32c6b23-f07e-4269-aac8-601e7aa090a7.png)
